services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-db.sql:/tmp/init.sql
    container_name: mi-sqlserver
    # SQL Server maneja su propio inicio

  backend:
    image: sso-backend-img
    build:
      context: ./SSO
      dockerfile: SSO.WebApi/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__SSOConnection=Server=sqlserver;Database=DBSSO;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - JwtSettings__Key=EstaEsUnaClaveSuperSecretaYDebeSerMuyLargaParaQueFuncione
      - JwtSettings__Issuer=SingleSignOn
      - JwtSettings__Audience=MisAplicaciones
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: mi-sso-backend
    depends_on:
      - sqlserver
    # El backend crea la BD y usuario
    command: >
      sh -c "
      echo 'Esperando a que SQL Server esté listo...' &&
      sleep 45s &&
      echo 'Creando base de datos y usuario...' &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong@Passw0rd -Q \"IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'DBSSO') CREATE DATABASE DBSSO\" &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong@Passw0rd -Q \"IF NOT EXISTS(SELECT * FROM sys.sql_logins WHERE name = 'user_dbsso') CREATE LOGIN user_dbsso WITH PASSWORD = 'MwDlw@C849uRsR#hg', CHECK_POLICY = OFF\" &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong@Passw0rd -d DBSSO -Q \"IF NOT EXISTS(SELECT * FROM sys.database_principals WHERE name = 'user_dbsso') CREATE USER user_dbsso FOR LOGIN user_dbsso; ALTER ROLE db_owner ADD MEMBER user_dbsso\" &&
      echo 'Iniciando aplicación...' &&
      dotnet SSO.WebApi.dll
      "

  frontend:
    image: sso-frontend-img
    build: 
      context: ./sso-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    container_name: mi-sso-frontend
    depends_on:
      - backend

volumes:
  sqlserver_data: