version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    container_name: sso-sqlserver
    restart: unless-stopped

  backend:
    image: sergiovallegarma/sso-backend:latest
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__SSOConnection=Server=sqlserver;Database=DBSSO;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - JwtSettings__Key=EstaEsUnaClaveSuperSecretaYDebeSerMuyLargaParaQueFuncione
      - JwtSettings__Issuer=SingleSignOn
      - JwtSettings__Audience=MisAplicaciones
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: sso-backend
    depends_on:
      - sqlserver
    restart: unless-stopped
    command: >
      sh -c "
      echo 'Esperando a que SQL Server esté listo...' &&
      sleep 45s &&
      echo 'Creando base de datos y usuario...' &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong@Passw0rd -Q \"IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'DBSSO') CREATE DATABASE DBSSO\" &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong@Passw0rd -Q \"IF NOT EXISTS(SELECT * FROM sys.sql_logins WHERE name = 'user_dbsso') CREATE LOGIN user_dbsso WITH PASSWORD = 'MwDlw@C849uRsR#hg', CHECK_POLICY = OFF\" &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong@Passw0rd -d DBSSO -Q \"IF NOT EXISTS(SELECT * FROM sys.database_principals WHERE name = 'user_dbsso') CREATE USER user_dbsso FOR LOGIN user_dbsso; ALTER ROLE db_owner ADD MEMBER user_dbsso\" &&
      echo 'Iniciando aplicación...' &&
      dotnet SSO.WebApi.dll
      "

  frontend:
    image: sergiovallegarma/sso-frontend:latest
    ports:
      - "80:80"
    container_name: sso-frontend
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlserver_data: