services:
  # 1. BASE DE DATOS SQL SERVER
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    container_name: mi-sqlserver

  # 2. BACKEND (.NET API)
  backend:
    image: sso-backend-img
    build:
      context: ./SSO
      dockerfile: SSO.WebApi/Dockerfile
    ports:
      - "5000:8080"
    environment:
      # Conecta al servicio 'sqlserver' definido arriba
      - ConnectionStrings__SSOConnection=Server=sqlserver;Database=DBSSO;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - JwtSettings__Key=EstaEsUnaClaveSuperSecretaYDebeSerMuyLargaParaQueFuncione
      - JwtSettings__Issuer=SingleSignOn
      - JwtSettings__Audience=MisAplicaciones
      # Configuración dinámica de CORS (IP de tu máquina)
      # Reemplaza 192.168.64.229 con tu IP real si cambia
      - AllowedOrigins=http://localhost:5173,http://192.168.32.1:5173
    container_name: mi-sso-backend
    depends_on:
      - sqlserver
    # Espera a que SQL arranque antes de iniciar la API
    command: >
      sh -c "echo 'Esperando SQL...' && sleep 15 && dotnet SSO.WebApi.dll"

  # 3. FRONTEND (React + Nginx)
  frontend:
    image: sso-frontend-img
    build: 
      context: ./sso-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      # Inyección de configuración en tiempo de ejecución (runtime)
      # Apunta al backend usando tu IP local para acceso desde red
      - API_URL=http://192.168.32.1:5000/api
    container_name: mi-sso-frontend
    depends_on:
      - backend

volumes:
  sqlserver_data: